usernameLocator = "input[name='username']"
passwordLocator = "input[name='password']"
btnLoginLocator = "button[id='btnLogin']"
logoutLocator = "a[class='btn btn-outline-info my-2 my-sm-0']"
login_errorLocator = "div[class='alert alert-danger mt-3']"

invoiceDetailsTitleLocator = "//h2[text()='Invoice Details']"
hotel_titleLocator = "//div[@class='container']//h4[@class='mt-5']"
invoice_dateLocator = "//li[span[text()='Invoice Date:']]"
due_dateLocator = "//li[span[text()='Due Date:']]"
booking_codeLocator = "//td[text()='Booking Code']/following-sibling::td"
room_codeLocator = "//td[text()='Room']/following-sibling::td"
total_stay_countLocator = "//td[text()='Total Stay Count']/following-sibling::td"
total_stay_amountLocator = "//td[text()='Total Stay Amount']/following-sibling::td"
check_inLocator = "//td[text()='Check-In']/following-sibling::td"
check_outLocator = "//td[text()='Check-Out']/following-sibling::td"
invoice_numberDetailsLocator = "h6[class='mt-2']"
deposit_nowtLocator = "//table[@class='table']//td[text()='Deposit Nowt']/following::tr/td[1]"
tax_vatLocator = "//table[@class='table']//td[text()='Deposit Nowt']/following::tr/td[2]"
total_amountLocator = "//table[@class='table']//td[text()='Deposit Nowt']/following::tr/td[3]"
customer_detailsLocator = "//h5[text()='Customer Details']/following-sibling::div"